---
- hosts: controller
  tasks:
  - name: Ensure node config dir exists
    file:
      path: ./nodes
      owner: alarm
      state: directory
      mode: 0755
  - name: Ensure project config file for all nodes
    command: cp --no-clobber ./examples/node.yml ./nodes/{{ item }}.yml
    loop: "{{ groups['compute_nodes'] }}"
  - name: Ensure cc_config file for all nodes
    command: cp --no-clobber ./examples/cc_config.xml ./nodes/cc_{{ item }}.xml
    loop: "{{ groups['compute_nodes'] }}"

- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Copy jlparse
    become: true
    copy:
      src: ./bin/utils/jlparse
      dest: /usr/local/bin/jlparse
      owner: root
      group: root
      mode: 0755

- hosts: controller
  tasks:
  - name: Assemble boinctui config file
    script: "./bin/makeboinctuicfg {{ groups['compute_nodes'] }}"
