---
- hosts: compute_nodes
  remote_user: farmer
  roles:
    - boinc_client

- hosts: controller
  tasks:
  - name: Ensure node config dir exists
    file:
      path: ./nodes
      owner: pi
      state: directory
      mode: 0755
  - name: Ensure config file for all nodes
    file:
      path: ./nodes/{{ item }}.yml
      src: ./examples/node.yml
      state: file
      owner: pi
      mode: 644
    loop: "{{ groups['compute_nodes'] }}"
