---
- hosts: compute
  remote_user: farmer

  tasks:
  - name: Add a boinc user
    become: true
    user:
      name: boinc
      comment: BOINC client
      create_home: false
      shell: /sbin/nologin
