---
- hosts: compute_nodes
  remote_user: farmer
  roles:
    - boinc_client

- hosts: controller
  tasks:
  - name: Ensure node config dir exists
    file:
      path: ./nodes
      owner: pi
      state: directory
      mode: 0755
  - name: Ensure config file for all nodes
    command: cp --no-clobber ./examples/node.yml ./nodes/{{ item }}.yml
    loop: "{{ groups['compute_nodes'] }}"
