---
- hosts: compute
  remote_user: farmer

  tasks:
  - name: Add a boinc user
    become: true
    user:
      name: boinc
      comment: BOINC client
      home: /var/lib/boinc
      shell: /sbin/nologin
