---
- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Upgrade system software
    become: true
    pacman:
      update-cache: yes
      upgrade: yes
  - name: Clear package cache
    become: true
    shell: yes | pacman -Scc
  #- name: Install additional software
  #  apk:
  #    name: x, y
  #    state: present
  - name: Upgrade ansible
    become: true
    pip:
      name: ansible
      state: latest
