---
- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Deploy gwagent
    become: true
    copy:
      src: /homefarm/files/gwagent-{{ ansible_architecture }}
      dest: /usr/local/bin/gwagent
      owner: root
      group: root
      mode: 0755
    when: ansible_architecture == hfarch
  - name: Create gwagent config dir
    become: true
    file:
      path: /etc/gnatwren
      owner: root
      group: root
      mode: 0755
      state: directory
    when: ansible_architecture == hfarch
  - name: Deploy gwagent config file
    become: true
    ansible.builtin.template:
      src: ./gwagent-config.json
      dest: /etc/gnatwren/agent-config.json
      owner: root
      group: root
      mode: 0644
    when: ansible_architecture == hfarch
    register: config
  - name: Deploy gwagent unit file
    become: true
    copy:
      src: ./files/gnatwren/assets/gnatwren-agent.service
      dest: /usr/lib/systemd/system/gnatwren-agent.service
      owner: root
      group: root
      mode: 0644
    when: ansible_architecture == hfarch
    register: unitfile
  - name: Reload unit files
    become: true
    systemd:
      daemon_reload: yes
    when: ansible_architecture == hfarch and unitfile.changed
  - name: Enable gwagent
    become: true
    service:
      name: gnatwren-agent
      enabled: yes
    when: ansible_architecture == hfarch and unitfile.changed
  - name: Restart gwagent
    become: true
    service:
      name: gnatwren-agent
      state: restarted
    when: ansible_architecture == hfarch and config.changed
