# This is a playbook for pulling, building, and deploying Gnatwren on
# Homefarm nodes. This is optional, and unless opted into, will never
# be executed.
---
- hosts: controller
  tasks:
  - name: Clone/pull Gnatwren repository
    git:
      repo: 'https://github.com/firepear/gnatwren.git'
      dest: /homefarm/files/gnatwren
  - name: Build agent for x86
    command: go build
    args:
      chdir: /homefarm/files/gnatwren/cmd/gwagent
  - name: Copy x86 executable to staging location
    copy:
      src: /homefarm/files/gnatwren/cmd/gwagent/gwagent
      dest: /homefarm/files/gwagent-x86_64
  - name: Build agent for armv7
    command: go build
    args:
      chdir: /homefarm/files/gnatwren/cmd/gwagent
    environment:
      GOOS: linux
      GOARCH: arm
  - name: Copy armv7 executable to staging location
    copy:
      src: /homefarm/files/gnatwren/cmd/gwagent/gwagent
      dest: /homefarm/files/gwagent-arm7h
  - name: Build gwquery
    command: go build
    args:
      chdir: /homefarm/files/gnatwren/cmd/gwquery
  - name: Deploy gwquery
    copy:
      src: /homefarm/files/gnatwren/cmd/gwquery/gwquery
      dest: /homefarm/bin/gwquery
      mode: 0755


- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Deploy gwagent
    become: true
    copy:
      src: /homefarm/files/gwagent-{{ ansible_architecture }}
      dest: /usr/local/bin/gwagent
      owner: root
      group: root
      mode: 0755
    when: ansible_architecture == hfarch
  - name: Create gwagent config dir
    become: true
    file:
      path: /etc/gnatwren
      owner: root
      group: root
      mode: 0755
      state: directory
    when: ansible_architecture == hfarch
  - name: Deploy gwagent config file
    become: true
    copy:
      src: ./files/gwagent-config.json
      dest: /etc/gnatwren/agent-config.json
      owner: root
      group: root
      mode: 0644
    when: ansible_architecture == hfarch
  - name: Deploy gwagent unit file
    become: true
    copy:
      src: ./files/gnatwren/assets/gnatwren-agent.service
      dest: /usr/lib/systemd/system/gnatwren-agent.service
      owner: root
      group: root
      mode: 0644
    when: ansible_architecture == hfarch
    register: unitfile
  - name: Reload unit files
    become: true
    systemd:
      daemon_reload: yes
    when: ansible_architecture == hfarch and unitfile.changed
  - name: Enable gwagent
    become: true
    service:
      name: gnatwren-agent
      enabled: yes
    when: ansible_architecture == hfarch and unitfile.changed
  - name: Restart gwagent
    become: true
    service:
      name: gnatwren-agent
      state: restarted
    when: ansible_architecture == hfarch and unitfile.changed
