---
- hosts: controller
  tasks:
  - name: Build gwgather
    command: go build
    args:
      chdir: /homefarm/files/gnatwren/cmd/gwgather
  - name: Deploy gwquery
    copy:
      src: /homefarm/files/gnatwren/cmd/gwgather/gwgather
      dest: /homefarm/bin/gwgather
      mode: 0755
  - name: Instantiate gwgather config
    copy:
      src: /homefarm/files/gnatwren/assets/gather-config.json
      dest: /homefarm/gwgather-config.json
      mode: 0644
      backup: yes
  - name: Build gwquery
    command: go build
    args:
      chdir: /homefarm/files/gnatwren/cmd/gwquery
  - name: Deploy gwquery
    copy:
      src: /homefarm/files/gnatwren/cmd/gwquery/gwquery
      dest: /homefarm/bin/gwquery
      mode: 0755
  - name: Create gwgather db dir
    become: true
    file:
      path: /var/lib/gnatwren.db
      owner: nobody
      group: nobody
      mode: 0755
      state: directory
