---
- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Copy mirrorlist
    become: true
    copy:
      src: ./srv/mirrorlist
      dest: /etc/pacman.d/mirrorlist
      owner: root
      group: root
      mode: 0644
  - name: Halt BOINC
    become: true
    service:
      name: boinc-client
      state: stopped
    ignore_errors: true
  - name: Upgrade system software
    become: true
    pacman:
      update-cache: yes
      upgrade: yes
  - name: Clear package cache
    become: true
    shell: yes | pacman -Scc
