---
- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Update pacman.conf
    become: true
    copy:
      src: ./srv/homefarm/pacman-{{ ansible_architecture }}.conf
      dest: /etc/pacman.conf
      owner: root
      group: root
      mode: 0644
  - name: Update BOINC client config
    become: true
    copy:
      src: ./nodes/{{ inventory_hostname }}-cc.xml
      dest: /var/lib/boinc/cc_config.xml
      owner: root
      group: root
      mode: 0644
    register: ccconfig
  - name: Update BOINC unit file
    become: true
    copy:
      src: ./files/boinc-client.service
      dest: /usr/lib/systemd/system/boinc-client.service
      owner: root
      group: root
      mode: 0644
    register: unitfile
  - name: Reload unit files
    become: true
    systemd:
      daemon_reload: yes
    when: unitfile.changed
  - name: Update Python common module
    become: true
    copy:
      src: ./files/homefarm.py
      dest: /usr/local/lib/homefarm.py
      owner: root
      group: root
      mode: 0644
  - name: Update query util
    become: true
    copy:
      src: ./bin/utils/query
      dest: /usr/local/bin/query
      owner: root
      group: root
      mode: 0755
  - name: Update boinccmdcmd
    become: true
    copy:
      src: ./bin/utils/boinccmdcmd
      dest: /usr/local/bin/boinccmdcmd
      owner: root
      group: root
      mode: 0755
  - name: Reload BOINC client config
    command: /bin/boinccmd --read_cc_config
    when: ccconfig.changed
  - name: Restart BOINC
    become: true
    service:
      name: boinc-client
      state: restarted
    when: unitfile.changed
