---
- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Copy mirrorlist
    become: true
    copy:
      src: ./srv/mirrorlist
      dest: /etc/pacman.d/mirrorlist
      owner: root
      group: root
      mode: 0644
  - name: Halt BOINC
    become: true
    service:
      name: boinc-client
      state: stopped
    ignore_errors: true
  - name: Upgrade system software
    become: true
    pacman:
      update-cache: yes
      upgrade: yes
  - name: Diff Homefarm and installed packages
    local_action: shell grep -v -f /homefarm/srv/arch/nodepkgs.txt  /homefarm/files/pkgs.txt
    register: newpkgs
  - name: Install new Homefarm packages
    become: true
    pacman:
      name: "{{ item }}"
      state: present
    with_items: "{{ newpkgs.results }}"
  - name: Clear package cache
    become: true
    shell: yes | pacman -Scc
