---
- hosts: boinc_nodes
  remote_user: farmer
  tasks:
    - name: Import project definitions
      include_vars:
        file: ./nodes/{{ inventory_hostname }}.yml
        name: node
    - name: Update project statuses
      become: true
      command: /usr/local/bin/boinccmdcmd /var/lib/boinc {{ item.url }} {{ item.user }} {{ item.email }} {{ item.passwd }} update
      loop: "{{ node.projects }}"
      when: item.state == "active"
