---
- hosts: controller
  tasks:
  - name: Sort localpkgs file
    shell:
      cmd: sort /homefarm/localpkgs-{{ hfarch }}.txt > l.s && mv l.s /homefarm/localpkgs-{{ hfarch }}.txt
  - name: Diff Homefarm and local packages
    shell:
      cmd: comm -1 /homefarm/files/pkgs-{{ hfarch }}.txt /homefarm/localpkgs-{{ hfarch }}.txt
      # hfarch gets passed in from 'ansible-playbook --extra-vars'
    ignore_errors: yes
    register: newpkgs

- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Copy mirrorlist
    become: true
    copy:
      src: ./srv/homefarm/mirrorlist-{{ ansible_architecture }}
      dest: /etc/pacman.d/mirrorlist
      owner: root
      group: root
      mode: 0644
  - name: Halt BOINC
    become: true
    service:
      name: boinc-client
      state: stopped
    ignore_errors: true
  - name: Upgrade system software
    become: true
    pacman:
      update-cache: yes
      upgrade: yes
  - name: Install new Homefarm packages
    become: true
    pacman:
      name: "{{ hostvars['localhost'].newpkgs.stdout_lines }}"
      state: present
    when: hostvars['localhost'].newpkgs.stdout != ""
  - name: Clear package cache
    become: true
    shell: yes | pacman -Scc
