---
- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Update project statuses
    become: true
    command: /usr/local/bin/boinccmdcmd /var/lib/boinc {{ item.url }} {{ item.user }} {{ item.email }} {{ item.passwd }} update
    when: "{{ item.state }}" == "active"
    loop: "{{ node.projects }}"
