---
- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Copy boinc unit file
    become: true
    copy:
      src: ./files/boinc-client.service
      dest: /usr/lib/systemd/system/boinc-client.service
      owner: root
      group: root
      mode: 0644
    register: unitfile
  - name: Reload unit files
    become: true
    systemd:
      daemon_reload: yes
    when: unitfile.changed
  - name: Copy python common module
    become: true
    copy:
      src: ./files/homefarm.py
      dest: /usr/local/lib/homefarm.py
      owner: root
      group: root
      mode: 0644
  - name: Copy query
    become: true
    copy:
      src: ./bin/utils/query
      dest: /usr/local/bin/query
      owner: root
      group: root
      mode: 0755
  - name: Copy boinccmdcmd
    become: true
    copy:
      src: ./bin/utils/boinccmdcmd
      dest: /usr/local/bin/boinccmdcmd
      owner: root
      group: root
      mode: 0755
  - name: Restart boinc
    become: true
    service:
      name: boinc-client
      state: restarted
    when: unitfile.changed
