---
- hosts: controller
  tasks:
  - name: Get BOINC and related packages
    shell:
      cmd: cat /homefarm/files/pkgs-compute.txt
    register: boincpkgs
  - name: Ensure node config dir exists
    file:
      path: ./nodes
      owner: root
      state: directory
      mode: 0755
  - name: Ensure project config file for all nodes
    command: cp --update=none ./files/node.yml ./nodes/{{ item }}.yml
    loop: "{{ groups['compute_nodes'] }}"
 - name: Ensure cc_config file for all nodes
    command: cp --update=none ./files/cc_config.xml ./nodes/{{ item }}-cc.xml
    loop: "{{ groups['compute_nodes'] }}"

- hosts: compute_nodes
  remote_user: farmer
  tasks:
  - name: Update pacman.conf
    become: true
    copy:
      src: ./srv/homefarm/pacman.conf
      dest: /etc/pacman.conf
      owner: root
      group: root
      mode: 0644
  - name: Install BOINC and related packages
    become: true
    pacman:
      name: "{{ hostvars['localhost'].boincpkgs.stdout_lines }}"
      state: present
      update_cache: yes
    when: hostvars['localhost'].boincpkgs.stdout != ""
  - name: Update BOINC client config
    become: true
    copy:
      src: ./nodes/{{ inventory_hostname }}-cc.xml
      dest: /var/lib/boinc/cc_config.xml
      owner: root
      group: root
      mode: 0644
    register: ccconfig
  - name: Update BOINC unit file
    become: true
    copy:
      src: ./files/boinc-client.service
      dest: /usr/lib/systemd/system/boinc-client.service
      owner: root
      group: root
      mode: 0644
    register: unitfile
  - name: Reload unit files
    become: true
    systemd:
      daemon_reload: yes
  - name: Enable BOINC client
    become: true
    ansible.builtin.systemd:
      name: boinc-client
      enabled: yes
      masked: no
  - name: Update Python common module
    become: true
    copy:
      src: ./files/homefarm.py
      dest: /usr/local/lib/homefarm.py
      owner: root
      group: root
      mode: 0644
  - name: Update query util
    become: true
    copy:
      src: ./bin/utils/query
      dest: /usr/local/bin/query
      owner: root
      group: root
      mode: 0755
  - name: Update boinccmdcmd
    become: true
    copy:
      src: ./bin/utils/boinccmdcmd
      dest: /usr/local/bin/boinccmdcmd
      owner: root
      group: root
      mode: 0755
  - name: Reload BOINC client config
    become: true
    shell: |
      cd /var/lib/boinc
      /bin/boinccmd --read_cc_config
    when: ccconfig.changed and (unitfile.changed is false)
  - name: Restart BOINC
    become: true
    service:
      name: boinc-client
      state: restarted
    when: unitfile.changed
