---
- hosts: compute_nodes
  remote_user: farmer

  tasks:
  - name: Import project definitions
    include_vars:
      file: ./nodes/{{ inventory_hostname }}.yml
      name: node

  - name: Make project modifications
    script: "./bin/boinccmdcmd /var/lib/boinc {{ item.url }} {{ item.user }} {{ item.email }} {{ item.passwd }} {{ item.state }}"
    loop: "{{ node.projects }}"
