---
- hosts: compute_nodes
  remote_user: farmer

  tasks:
  - name: Import project definitions
    include_vars:
      file: projects.yml
      name: farmprojs

  - name: Import BOINC vars
    include_vars:
      file: roles/boinc_client/vars/main.yml
      name: boincvars

  - name: Make project modifications
    script: "./scripts/boinccmdcmd {{ boincvars.boinc._work_dir }} {{ item.url }} {{ item.email }} {{ item.passwd }} {{ item.status }}"
    loop: "{{ farmprojs }}"

# after the actual project update work is done, this playbook should
# be to update the controller's boinctui config.
#
# - task to create /etc/ansible/facts.d
# - task to create static JSON file in that dir, containing the value of /var/lib/boinc/gui_rpc_auth.cfg
#
#   { "gui_auth": "HEXKEY" }
#
# might need dummy task like this to collect facts, depending on
# structure
#
# - hosts: collectors
#   name: Gather facts from collectors
#   tasks: [ ]
