---
- import_tasks: boincuser.yml

- name: Install BOINC dependencies
  become: true
  apk:
    name: "{{ item }}"
    update_cache: yes
  with_items:
    - libtool
    - automake
    - libcurl
    - curl-dev
    - g++

- name: Check installed BOINC version
  shell: "/usr/local/bin/boinc --version | grep {{ boinc_version }}"
  register: boinc_version_match
  changed_when: false
  ignore_errors: true

- name: Halt BOINC if version has changed
  become: true
  service:
    name: boinc-client
    state: stopped
  ignore_errors: true
  when: boinc_version_match is failed

- name: Ensure BOINC src dir exists
  become: true
  file:
    path: "{{ boinc_src_dir }}"
    owner: farmer
    state: directory
    mode: 0755
  when: boinc_version_match is failed

- name: Download BOINC source
  get_url:
    url: "{{ boinc_src_url }}"
    dest: "{{ boinc_src_file }}"
    sha256sum: "{{ boinc_src_sha256 }}"
  when: boinc_version_match is failed

- name: Extract BOINC source
  unarchive:
    src: "{{ boinc_src_file }}"
    dest: "{{ boinc_src_dir }}"
    remote_src: true
    creates: "{{ boinc_src_unpack_dir }}"
  when: boinc_version_match is failed

- name: Preconfigure BOINC source tree
  command:
    "bash -lc './_autosetup'"
  args:
    chdir: "{{ boinc_src_unpack_dir }}"
  register: boinc_preconfigured
  when: boinc_version_match is failed

- name: Configure BOINC source tree
  command:
    "bash -lc './configure --disable-server --disable-manager'"
  args:
    chdir: "{{ boinc_src_unpack_dir }}"
  register: boinc_configured
  when: boinc_preconfigured.changed

- name: Make and install BOINC
  become: true
  command:
    "bash -lc 'make && make install'"
  args:
    chdir: "{{ boinc_src_unpack_dir }}"
  when: boinc_configured.changed
  register: boinc_built
  notify: Restart BOINC

- name: Clean BOINC src dir
  become: true
  command:
    "bash -lc 'rm -rf {{ boinc_src_file }} {{ boinc_src_unpack_dir }}'"
  when: boinc_built.changed

- name: Install improved BOINC init script
  become: true
  template:
    src: boinc-client.j2
    dest: /usr/local/etc/init.d/boinc-client
    owner: root
    group: root
    mode: 0755
  register: boinc_init
  notify: Restart BOINC

- name: Enable BOINC in openrc
  become: true
  service:
    name: boinc-client
    enabled: yes
  when: boinc_init.changed

- name: BOINC startup
  become: true
  service:
    name: boinc-client
    state: started
  when: boinc_version_match is failed

- import_tasks: copyguiauth.yml
